name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        rust: [1.76.0]
        include:
          - os: ubuntu-22.04
            rust: 1.76.0

    name: "Formatting"
    runs-on: ${{ matrix.os }}

    steps:
    - name: Fetch repo
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        components: rustfmt
        toolchain: ${{ matrix.rust }}

    - name: rustfmt
      run: |
        cargo fmt -- --check

  checks:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        rust: [1.76.0]
        include:
          - os: ubuntu-22.04
            rust: 1.76.0
    
    name: Checks
    runs-on: ${{ matrix.os }}

    steps:
    - name: Fetch repo
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        components: rustfmt, clippy llvm-tools-preview
        toolchain: ${{ matrix.rust }}

    - name: Install cargo-nextest and cargo-llvm-cov
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest,cargo-llvm-cov

    - name: Clippy
      uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-review'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        clippy_flags: --all-targets -- -Dwarnings
        filter_mode: nofilter

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo llvm-cov nextest --all-features --workspace --lcov --output-path tests.lcov

    - name: Upload Codecov
      uses: codecov/codecov-action@v4
      with:
        files: tests.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
