name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        rust: [1.76.0]
        include:
          - os: ubuntu-22.04
            rust: 1.76.0
    
    name: RFashSpeech checks ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Fetch repo
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        components: rustfmt, clippy llvm-tools-preview
        toolchain: ${{ matrix.rust }}

    - name: Install cargo-nextest and cargo-llvm-cov
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest,cargo-llvm-cov

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo llvm-cov nextest --lcov --output-path tests.lcov

    - name: Upload Codecov
      uses: codecov/codecov-action@v4
      with:
        files: tests.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
